Repository googleapis/google-api-python-client, pull requests merged in 2020-03, with the labels that each got.

#832 chore: move kokoro configs
  .kokoro/continuous/common.cfg
  .kokoro/continuous/continuous.cfg
  .kokoro/presubmit/common.cfg
  .kokoro/presubmit/presubmit.cfg
Labels: cla: yes

#813 fix: exclude 308s from httplib2 redirect codes list
  googleapiclient/http.py
  setup.py
  tests/test_http.py
Labels: cla: yes

#837 chore: release 1.7.12
  CHANGELOG
  googleapiclient/__init__.py
Labels: cla: yes

#829 feat: add client_options support for api endpoint override
  googleapiclient/discovery.py
  setup.py
  tests/test_discovery.py
  tests/test_http.py
Labels: cla: yes, kokoro:force-run

#841 fix: don't set http.redirect_codes if the attr doesn't exist
  googleapiclient/http.py
  setup.py
Labels: automerge, cla: yes

#842 chore: release v1.8.0
  CHANGELOG
  googleapiclient/__init__.py
Labels: cla: yes

#833 docs: Add note about Google Firebase Admin API
  README.md
Labels: cla: yes

#822 fix: Adding ConnectionError to retry mechanism
  googleapiclient/http.py
  tests/test_http.py
Labels: cla: yes
