Repository googleapis/google-api-python-client, pull requests merged in 2020-12, with the labels that each got.

#1117 fix: handle error on service not enabled
  googleapiclient/http.py
Labels: automerge, cla: yes

#1120 docs: update guidance on service accounts
  docs/oauth-server.md
Labels: cla: yes

#1125 fix: Use logging level info when file_cache is not available
  googleapiclient/discovery_cache/__init__.py
Labels: cla: yes

#1122 chore: add constraints file
  testing/constraints-3.10.txt
  testing/constraints-3.11.txt
  testing/constraints-3.6.txt
  testing/constraints-3.7.txt
  testing/constraints-3.8.txt
  testing/constraints-3.9.txt
Labels: automerge, cla: yes

#1126 fix: Improve support for error_details
  googleapiclient/errors.py
  tests/test_errors.py
Labels: automerge, cla: yes

#1127 fix: MediaFileUpload error if file does not exist
  googleapiclient/http.py
  tests/test_http.py
Labels: automerge, cla: yes

#1135 docs: Reduce noisy changes in docs regen
  describe.py
  googleapiclient/discovery.py
  googleapiclient/schema.py
  tests/test_schema.py
Labels: automerge, cla: yes, type: docs

#1141 docs: fix regression with incorrect args order in docs
  describe.py
Labels: automerge, cla: yes

#1142 docs: Delete redundant oauth-web.md
  docs/README.md
  docs/api-keys.md
  docs/oauth-web.md
Labels: cla: yes
