Repository googleapis/google-api-python-client, pull requests merged in 2020-11, with the labels that each got.

#1083 docs: Change error parsing to check for 'message'
  docs/start.md
  googleapiclient/errors.py
  tests/test_errors.py
  tests/test_http.py
Labels: automerge, cla: yes, semver: patch

#1090 Add OAuth scopes link start.md
  docs/start.md
Labels: cla: yes

#1088 docs: Update oauth docs to include snippet to get email address of authenticated user
  docs/oauth.md
Labels: automerge, cla: yes

#1092 docs: Update Webmasters API sample
  samples/searchconsole/search_analytics_api_sample.py
Labels: automerge, cla: yes, samples

#1005 docs: add httplib2 authorization to thread_safety
  docs/thread_safety.md
Labels: api: docs, automerge, cla: yes

#1100 docs: fix typo in thread safety example code
  docs/thread_safety.md
Labels: automerge, cla: yes

#1104 feat: Update synth.py to copy discovery files from discovery-artifact-manager
  synth.py
Labels: automerge, cla: yes

#1112 docs: fix MediaIoBaseUpload broken link
  docs/media.md
Labels: automerge, cla: yes
