Repository googleapis/google-api-python-client, pull requests merged in 2020-04, with the labels that each got.

#860 Fix "byteswarning" errors in http and model modules
  googleapiclient/http.py
  googleapiclient/model.py
Labels: automerge, cla: yes

#863 fix: replace '-' in method names with '_'
  googleapiclient/discovery.py
Labels: cla: yes

#828 docs: fix simple typo: occured -> occurred
  googleapiclient/errors.py
  googleapiclient/http.py
  samples/analytics/management_v3_reference.py
Labels: automerge, cla: yes

#801 build: support using python3 to generate docs
  describe.py
Labels: automerge, cla: yes

#815 docs: added navigation to index.md
  docs/dyn/index.md
Labels: automerge, cla: yes

#871 Remove apiclient.__version__
  apiclient/__init__.py
Labels: automerge, cla: yes

#816 docs: fix link typo in docs
  docs/oauth.md
Labels: automerge, cla: yes

#869 docs: drop 3.4 from README
  README.md
Labels: cla: yes

#823 docs: Update "Google Apps" references and add DwD example
  docs/oauth-server.md
Labels: cla: yes

#802 docs: fix unescaped html tag
  describe.py
Labels: cla: yes

#878 chore: release 1.8.2
  CHANGELOG.md
  setup.py
Labels: autorelease: pending, cla: yes

#885 fix: downgrade repetitive logging calls to debug
  googleapiclient/discovery.py
Labels: cla: yes
