Repository googleapis/google-api-python-client, pull requests merged in 2020-05, with the labels that each got.

#890 fix: update GitHub org to googleapis from google
  contributing.html
Labels: cla: yes

#900 test: use self.MOCK_CREDENTIALS in tests
  tests/test_discovery.py
Labels: cla: yes, type: cleanup

#903 fix: don't try to import GAE API in other environments
  googleapiclient/discovery_cache/__init__.py
  tests/test_discovery.py
Labels: cla: yes

#901 fix: the turn down date for global batch uri
  googleapiclient/http.py
Labels: automerge, cla: yes

#892 docs: changed http to https in setup, updated github links
  CHANGELOG.md
  docs/epy/googleapiclient.http-pysrc.html
  docs/mocks.md
  googleapiclient/http.py
  setup.py
Labels: automerge, cla: yes

#906 docs: fix typo in positional method docstring
  googleapiclient/_helpers.py
Labels: automerge, cla: yes, type: docs

#921 chore(python): remove one remaining extra bash line (#565)
  .kokoro/release.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#924 feat: add templates for python samples projects (#506)
  .kokoro/samples/lint/common.cfg
  .kokoro/samples/lint/continuous.cfg
  .kokoro/samples/lint/periodic.cfg
  .kokoro/samples/lint/presubmit.cfg
  .kokoro/samples/python3.6/common.cfg
  .kokoro/samples/python3.6/continuous.cfg
  .kokoro/samples/python3.6/periodic.cfg
  .kokoro/samples/python3.6/presubmit.cfg
  .kokoro/samples/python3.7/common.cfg
  .kokoro/samples/python3.7/continuous.cfg
  .kokoro/samples/python3.7/periodic.cfg
  .kokoro/samples/python3.7/presubmit.cfg
  .kokoro/samples/python3.8/common.cfg
  .kokoro/samples/python3.8/continuous.cfg
  .kokoro/samples/python3.8/periodic.cfg
  .kokoro/samples/python3.8/presubmit.cfg
  .kokoro/test-samples.sh
  synth.metadata
Labels: cla: yes, context: full
