Repository googleapis/google-api-python-client, pull requests merged in 2021-03, with the labels that each got.

#1205 chore(v1): Pin rsa to 4.5 for Python 2.7 compatibility
  setup.py
  tests/test__auth.py
Labels: automerge, cla: yes

#1206 chore: remove discovery artifact copy from synth.py
  synth.py
Labels: automerge, cla: yes

#1213 docs: add a link to the migration guide in the changelog
  CHANGELOG.md
Labels: automerge, cla: yes

#1216 fix: add static discovery docs
  MANIFEST.in
Labels: automerge, cla: yes

#1221 fix: Include discovery artifacts in published package
  setup.py
Labels: automerge, cla: yes

#1223 chore: run synthtool
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes

#1226 docs: Distinguish between public/private docs in 2.0 guide
  UPGRADING.md
Labels: automerge, cla: yes

#1247 chore: Update docs/dyn index
  docs/dyn/index.md
  synth.metadata
Labels: automerge, cla: yes

#1231 fix: fix .close()
  googleapiclient/discovery.py
  setup.py
  tests/test_discovery.py
Labels: automerge, cla: yes

#1251 chore: fix broken links in README.md
  README.md
Labels: automerge, cla: yes

#1252 docs: Update README to promote cloud client libraries
  README.md
  UPGRADING.md
Labels: automerge, cla: yes

#1244 fix: Resolve issue where num_retries would have no effect
  googleapiclient/http.py
  tests/test_http.py
Labels: automerge, cla: yes

#1185 feat: add status_code property on http error handling
  docs/start.md
  googleapiclient/errors.py
  tests/test_errors.py
Labels: automerge, cla: yes

#1254 chore: Update docs/dyn index
  docs/dyn/index.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#1258 fix: correct api version in oauth-installed.md
  docs/oauth-installed.md
Labels: automerge, cla: yes

#1261 fix: Change default of `static_discovery` when `discoveryServiceUrl` set
  UPGRADING.md
  googleapiclient/discovery.py
  tests/test_discovery.py
Labels: automerge, cla: yes

#1271 chore: Remove docs session
  noxfile.py
  synth.py
Labels: cla: yes
