Repository googleapis/google-api-python-client, pull requests merged in 2021-07, with the labels that each got.

#1434 docs: add recommendation to use v2.x and static discovery artifacts
  README.md
  UPGRADING.md
Labels: automerge, cla: yes

#1437 chore: remove unused code
  googleapiclient/discovery.py
  noxfile.py
Labels: automerge: exact, cla: yes

#1429 chore: Moving GCE API samples from python-docs-samples (b/191786905)
  samples/README.md
  samples/compute/README.md
  samples/compute/create_instance.py
  samples/compute/create_instance_test.py
  samples/compute/requirements-test.txt
  samples/compute/requirements.txt
  samples/compute/startup-script.sh
Labels: cla: yes, samples

#1449 fix(deps): pin 'google-{api,cloud}-core', 'google-auth' to allow 2.x versions
  setup.py
Labels: automerge, cla: yes

#1452 fix: drop six dependency
  apiclient/__init__.py
  googleapiclient/_helpers.py
  googleapiclient/channel.py
  googleapiclient/discovery.py
  googleapiclient/http.py
  googleapiclient/mimeparse.py
  googleapiclient/model.py
  googleapiclient/schema.py
  samples/compute/create_instance.py
  setup.py
  testing/constraints-3.6.txt
  tests/test__helpers.py
  tests/test_discovery.py
  tests/test_http.py
  tests/test_json_model.py
  tests/test_protobuf_model.py
Labels: automerge, cla: yes

#1461 docs: update license to be Apache-2.0 compliant
  LICENSE
Labels: automerge, cla: yes
