Repository googleapis/google-api-python-client, pull requests merged in 2021-01, with the labels that each got.

#1147 fix: Catch ECONNRESET and other errors more reliably
  googleapiclient/http.py
  tests/test_http.py
Labels: automerge, cla: yes

#1161 fix: replace deprecated socket.error with OSError
  googleapiclient/http.py
  tests/test_http.py
Labels: automerge, cla: yes

#1109 feat: Add support for using static discovery documents
  describe.py
  docs/start.md
  googleapiclient/discovery.py
  googleapiclient/discovery_cache/__init__.py
  tests/test_discovery.py
  tests/test_http.py
  tests/test_mocks.py
Labels: automerge, cla: yes

#1166 chore(python): skip docfx in main presubmit
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#1171 chore: Add header checker config
  .github/header-checker-lint.yml
  docs/dyn/index.md
  synth.metadata
Labels: automerge, cla: yes, context: partial

#1175 build: migrate to flakybot
  .kokoro/test-samples.sh
  .kokoro/trampoline_v2.sh
Labels: cla: yes
