Repository googleapis/google-api-python-client, pull requests merged in 2021-09, with the labels that each got.

#1512 chore: removing owlbot directives for conversion to main
  .github/.OwlBot.lock.yaml
  owlbot.py
Labels: cla: yes

#1513 fix: remove repeated calls to self._get_reason
  googleapiclient/errors.py
Labels: cla: yes, automerge: exact

#1536 chore: relocate owl bot post processor
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
Labels: cla: yes, automerge
