Repository googleapis/google-api-python-client, pull requests merged in 2021-04, with the labels that each got.

#1281 feat: Adds support for errors.py to also use 'errors' for error_details
  googleapiclient/errors.py
  tests/test_errors.py
  tests/test_http.py
Labels: automerge, cla: yes

#1278 chore: fix typo in README.md
  docs/README.md
Labels: automerge, cla: yes

#1277 chore: Update synth.metadata
  synth.metadata
Labels: automerge, cla: yes

#1287 chore: start tracking obsolete files
  synth.metadata
Labels: cla: yes, context: full

#1288 chore: add constraints file check for python samples
  .github/header-checker-lint.yml
  synth.metadata
Labels: cla: yes, context: full, samples

#1293 build: use PyPI API token in secret manager
  .kokoro/release.sh
  .kokoro/release/common.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#1292 chore: prevent normalization of semver versioning
  setup.py
Labels: automerge, cla: yes

#1295 test: update nox file to build and test wheels
  noxfile.py
Labels: automerge, cla: yes

#1286 chore: add scripts to update discovery artifacts
  describe.py
  noxfile.py
  scripts/README.md
  scripts/buildprbody.py
  scripts/changesummary.py
  scripts/changesummary_test.py
  scripts/createcommits.sh
  scripts/requirements.txt
  scripts/test_resources/current_artifacts_dir/bigquery.v2.json
  scripts/test_resources/current_artifacts_dir/cloudtasks.v2.json
  scripts/test_resources/new_artifacts_dir/bigquery.v2.json
  scripts/test_resources/new_artifacts_dir/drive.v3.json
  scripts/updatediscoveryartifacts.py
Labels: automerge, cla: yes

#1187 chore: Add github action to update discovery artifacts
  .github/workflows/main.yml
Labels: automerge, cla: yes

#1305 chore(revert): "chore: prevent normalization of semver versioning"
  setup.py
Labels: automerge, cla: yes

#1312 chore: Github action should only run once per day
  .github/workflows/main.yml
Labels: automerge, cla: yes

#1321 test: always use MOCK_CREDENTIALS in tests
  tests/test_discovery.py
Labels: cla: yes

#1320 chore: add auto-approve bot
  .github/CODEOWNERS
  .github/auto-approve.yml
Labels: automerge, cla: yes

#1324 fix: preventing accessing predefined discovery URLs when override is provided
  googleapiclient/discovery.py
Labels: automerge, cla: yes
